#file: noinspection SpellCheckingInspection
http:
  port: 8888

data:
  postgres:
    test-container: false
    port: 5432
    username: yazinnnn
    password: yazinnnn
    db: yazinnnn
    jdbc-url: jdbc:postgresql://localhost/yazinnnn
